import type { Actor } from '../types'

export const mockActors: Actor[] = [
  {
    id: 'vladimir-putin',
    name: 'Vladimir Putin',
    type: 'individual',
    countries: ['russia'],
    role: 'President of the Russian Federation',
    riskContribution: 'high',
    description:
      'Putin has led Russia since 2000, consolidating executive authority and pursuing a revisionist foreign policy centered on restoring Russia\'s sphere of influence. His decision to launch the full-scale Ukraine invasion in February 2022 fundamentally altered European security. Nuclear signaling is a consistent element of his strategic posture.',
    affiliations: ['kremlin', 'united-russia'],
  },
  {
    id: 'xi-jinping',
    name: 'Xi Jinping',
    type: 'individual',
    countries: ['china'],
    role: 'General Secretary, President of the PRC',
    riskContribution: 'high',
    description:
      'Xi has consolidated unprecedented personal authority over Chinese politics, military, and economy. His stated goal of "national rejuvenation" includes reunification with Taiwan. His third term removes previous norms of leadership transition, creating long-term systemic uncertainty.',
    affiliations: ['chinese-communist-party', 'peoples-liberation-army'],
  },
  {
    id: 'kim-jong-un',
    name: 'Kim Jong-un',
    type: 'individual',
    countries: ['north-korea'],
    role: 'Supreme Leader of North Korea',
    riskContribution: 'high',
    description:
      'Kim has overseen significant expansion of North Korea\'s nuclear and missile capabilities. He has enshrined nuclear status in the constitution and abandoned reunification rhetoric. Military cooperation with Russia has provided economic relief and technological exchange opportunities.',
    affiliations: ['korean-workers-party'],
  },
  {
    id: 'russian-armed-forces',
    name: 'Russian Armed Forces',
    type: 'state',
    countries: ['russia'],
    role: 'Primary conventional military instrument of Russian state policy',
    riskContribution: 'high',
    description:
      'The Russian Armed Forces have demonstrated significant attrition in Ukraine but have adapted tactics and maintained offensive pressure through mass mobilization. Drone and missile strikes on Ukrainian civilian infrastructure remain a core element of strategy. Estimated 300,000+ casualties since February 2022.',
    affiliations: ['russian-ministry-of-defense'],
  },
  {
    id: 'irgc',
    name: 'Islamic Revolutionary Guard Corps',
    type: 'state',
    countries: ['iran'],
    role: 'Elite Iranian military and intelligence organization',
    riskContribution: 'high',
    description:
      'The IRGC is the primary instrument of Iranian strategic influence, managing the proxy network spanning Lebanon (Hezbollah), Yemen (Houthis), Iraq (PMF), and Gaza (Hamas). The IRGC Quds Force coordinates extraterritorial operations. The corps also controls significant Iranian economic assets.',
    affiliations: ['iranian-government'],
  },
  {
    id: 'peoples-liberation-army',
    name: "People's Liberation Army",
    type: 'state',
    countries: ['china', 'taiwan'],
    role: 'Chinese military force under CCP control',
    riskContribution: 'high',
    description:
      'The PLA has undergone the most significant modernization in its history under Xi. Taiwan Strait operations have increased in frequency and complexity. The PLA Navy has become a genuine blue-water force. Anti-access/area denial capabilities are designed to deter US intervention in a Taiwan contingency.',
    affiliations: ['chinese-communist-party'],
  },
  {
    id: 'volodymyr-zelensky',
    name: 'Volodymyr Zelensky',
    type: 'individual',
    countries: ['ukraine'],
    role: 'President of Ukraine',
    riskContribution: 'medium',
    description:
      'Zelensky has led Ukraine\'s resistance to Russian invasion with significant international diplomatic success. His communications strategy has been central to maintaining Western support. War-time governance has concentrated executive authority, raising concerns about democratic norms while operational necessity is acknowledged.',
    affiliations: ['ukrainian-government'],
  },
  {
    id: 'nicolas-maduro',
    name: 'Nicolás Maduro',
    type: 'individual',
    countries: ['venezuela'],
    role: 'President of Venezuela',
    riskContribution: 'medium',
    description:
      'Maduro has maintained power through a combination of security force loyalty, electoral manipulation, and repression of opposition. His government\'s economic mismanagement has produced one of the worst peacetime economic collapses in history. The Essequibo territorial claim is increasingly used as a nationalist political instrument.',
    affiliations: ['psuv', 'venezuelan-government'],
  },
  {
    id: 'donald-trump',
    name: 'Donald Trump',
    type: 'individual',
    countries: ['united-states'],
    role: 'President of the United States (47th)',
    riskContribution: 'high',
    description:
      'Trump returned to the presidency in January 2025 pursuing an America First agenda: broad tariff escalation, recalibrated NATO commitments, immigration enforcement, and direct engagement with North Korea and Russia. His administration has significantly altered U.S. positions on Ukraine aid, Middle East diplomacy, and multilateral institutions. High policy unpredictability is a defining characteristic.',
    affiliations: ['republican-party', 'us-government'],
  },
  {
    id: 'jd-vance',
    name: 'JD Vance',
    type: 'individual',
    countries: ['united-states'],
    role: 'Vice President of the United States',
    riskContribution: 'medium',
    description:
      'Vance is a central figure in Trump\'s second-term foreign policy, having publicly questioned U.S. support for Ukraine and articulated an America First foreign policy vision. His role in administration decisions on NATO burden-sharing and Ukraine negotiations is significant.',
    affiliations: ['republican-party', 'us-government'],
  },
  {
    id: 'benjamin-netanyahu',
    name: 'Benjamin Netanyahu',
    type: 'individual',
    countries: ['israel'],
    role: 'Prime Minister of Israel',
    riskContribution: 'high',
    description:
      'Netanyahu has led Israel\'s military response to the October 7, 2023 Hamas attacks, overseeing an extended Gaza military campaign and strikes on Iranian territory. He faces domestic corruption charges and is navigating a coalition dependent on far-right partners who oppose Gaza ceasefire terms. His ICC arrest warrant complicates international travel.',
    affiliations: ['likud', 'israeli-government'],
  },
  {
    id: 'ali-khamenei',
    name: 'Ali Khamenei',
    type: 'individual',
    countries: ['iran'],
    role: 'Supreme Leader of Iran',
    riskContribution: 'high',
    description:
      'Khamenei is the ultimate decision-maker in Iran, holding authority over the military, nuclear program, and proxy network strategy. He has presided over Iran\'s first direct missile and drone attacks on Israeli territory (April and October 2024) and continued nuclear program advancement. Succession planning is a growing concern given his age.',
    affiliations: ['iranian-government', 'irgc'],
  },
  {
    id: 'masoud-pezeshkian',
    name: 'Masoud Pezeshkian',
    type: 'individual',
    countries: ['iran'],
    role: 'President of Iran',
    riskContribution: 'medium',
    description:
      'Pezeshkian, a reformist, was elected president in July 2024. He has signaled willingness to negotiate on nuclear issues and ease domestic restrictions, but remains subordinate to Khamenei on all strategic matters. His influence is constrained by hardliner institutions.',
    affiliations: ['iranian-government'],
  },
  {
    id: 'narendra-modi',
    name: 'Narendra Modi',
    type: 'individual',
    countries: ['india'],
    role: 'Prime Minister of India',
    riskContribution: 'medium',
    description:
      'Modi\'s BJP government pursues strategic autonomy, maintaining close ties with Russia while deepening the U.S.-India partnership. India abstains on Ukraine votes and continues Russian energy imports. Domestic Hindu nationalist policies are reshaping Indian secularism. India-China border tensions simmer despite recent diplomatic stabilization.',
    affiliations: ['bjp', 'indian-government'],
  },
  {
    id: 'mohammed-bin-salman',
    name: 'Mohammed bin Salman',
    type: 'individual',
    countries: ['saudi-arabia'],
    role: 'Crown Prince and Prime Minister of Saudi Arabia',
    riskContribution: 'medium',
    description:
      'MBS has consolidated unprecedented authority over Saudi Arabia and pursued Vision 2030 economic transformation alongside continued authoritarian governance. Israel normalization was disrupted by the Gaza war but remains a long-term objective. Saudi-Iran rapprochement (brokered by China in 2023) has reshaped Gulf dynamics.',
    affiliations: ['saudi-royal-family', 'saudi-government'],
  },
  {
    id: 'recep-erdogan',
    name: 'Recep Tayyip Erdoğan',
    type: 'individual',
    countries: ['turkey'],
    role: 'President of Turkey',
    riskContribution: 'medium',
    description:
      'Erdoğan plays a complex balancing role as a NATO member maintaining ties with Russia, brokering the Black Sea Grain Initiative, and expanding Turkish influence from Libya to Central Asia. Turkey\'s drone technology exports have become a significant geopolitical instrument. Domestic economic management remains a persistent vulnerability.',
    affiliations: ['akp', 'turkish-government'],
  },
  {
    id: 'hamas',
    name: 'Hamas',
    type: 'non-state',
    countries: ['palestine'],
    role: 'Designated terrorist organization and Gaza governing authority',
    riskContribution: 'high',
    description:
      'Hamas carried out the October 7, 2023 attack on Israel — the deadliest attack on Jewish people since the Holocaust. Its military wing has been significantly degraded by Israeli operations, though it retains organizational capacity. Political leadership is based in Qatar.',
    affiliations: ['iran', 'irgc'],
  },
  {
    id: 'hezbollah',
    name: 'Hezbollah',
    type: 'non-state',
    countries: ['lebanon'],
    role: 'Iran-backed Lebanese militant organization and political party',
    riskContribution: 'high',
    description:
      'Hezbollah suffered significant losses in 2024 with the killing of Secretary-General Hassan Nasrallah and multiple senior commanders in Israeli strikes. Its missile arsenal, while degraded, remains the largest non-state rocket force in the world. Ceasefire with Israel is fragile.',
    affiliations: ['iran', 'irgc'],
  },
  {
    id: 'houthis',
    name: 'Houthi Movement (Ansar Allah)',
    type: 'non-state',
    countries: ['yemen'],
    role: 'Iran-backed Yemeni armed movement controlling northern Yemen',
    riskContribution: 'high',
    description:
      'The Houthis have launched hundreds of drone and missile attacks on Red Sea shipping since late 2023, disrupting global trade routes. They control most of northern Yemen including Sanaa. U.S. and UK strikes have not significantly degraded their capabilities. They frame their attacks as solidarity with Gaza.',
    affiliations: ['iran', 'irgc'],
  },
  {
    id: 'idf',
    name: 'Israel Defense Forces',
    type: 'state',
    countries: ['israel'],
    role: 'Military forces of the State of Israel',
    riskContribution: 'high',
    description:
      'The IDF has conducted an extensive military campaign in Gaza since October 2023, achieving significant degradation of Hamas and Hezbollah military capacity but facing international legal scrutiny over civilian casualties. The IDF has also struck Iranian territory directly for the first time in history.',
    affiliations: ['israeli-government'],
  },
  {
    id: 'antonio-guterres',
    name: 'António Guterres',
    type: 'individual',
    countries: [],
    role: 'UN Secretary-General',
    riskContribution: 'low',
    description:
      'Guterres has been vocal on Gaza, climate, and Ukraine, repeatedly calling for ceasefires and humanitarian access. His calls have had limited operational impact given Security Council dynamics but carry significant moral authority.',
    affiliations: ['united-nations'],
  },
]
