import type { Country } from '../types'

export const mockCountries: Country[] = [
  {
    id: 'russia',
    slug: 'russia',
    name: 'Russia',
    iso2: 'RU',
    iso3: 'RUS',
    region: 'eastern-europe',
    overallRiskScore: 91,
    riskLevel: 'critical',
    riskCategories: {
      political: 88,
      military: 96,
      economic: 79,
      social: 74,
      environmental: 42,
    },
    summary:
      'Russia continues its full-scale military offensive in Ukraine, now entering its third year. Domestic political consolidation under Putin remains absolute following the suppression of the Wagner mutiny. Western sanctions have reshaped trade flows but failed to collapse the economy. Nuclear signaling remains a persistent escalation risk.',
    keyActors: ['vladimir-putin', 'russian-armed-forces', 'wagner-group'],
    capital: 'Moscow',
    lastUpdated: '2026-03-30',
    alertCount: 14,
    activeForecastCount: 5,
    population: 143_800_000,
  },
  {
    id: 'ukraine',
    slug: 'ukraine',
    name: 'Ukraine',
    iso2: 'UA',
    iso3: 'UKR',
    region: 'eastern-europe',
    overallRiskScore: 89,
    riskLevel: 'critical',
    riskCategories: {
      political: 72,
      military: 98,
      economic: 85,
      social: 81,
      environmental: 67,
    },
    summary:
      'Ukraine is engaged in an existential defensive war against Russia. Despite significant territorial losses in the east, Ukrainian forces have demonstrated resilience and conducted successful cross-border operations. Western military aid remains critical to operational capacity. Economic reconstruction needs are estimated at over $500 billion.',
    keyActors: ['volodymyr-zelensky', 'ukrainian-armed-forces'],
    capital: 'Kyiv',
    lastUpdated: '2026-03-30',
    alertCount: 18,
    activeForecastCount: 6,
    population: 37_600_000,
  },
  {
    id: 'china',
    slug: 'china',
    name: 'China',
    iso2: 'CN',
    iso3: 'CHN',
    region: 'east-asia',
    overallRiskScore: 73,
    riskLevel: 'high',
    riskCategories: {
      political: 65,
      military: 78,
      economic: 61,
      social: 58,
      environmental: 55,
    },
    summary:
      'China faces growing geopolitical pressure over Taiwan, South China Sea disputes, and economic competition with the United States. Xi Jinping\'s third term consolidation has reduced internal dissent channels. Property sector instability continues to weigh on growth. Military modernization accelerates with a focus on power projection capabilities.',
    keyActors: ['xi-jinping', 'peoples-liberation-army'],
    capital: 'Beijing',
    lastUpdated: '2026-03-28',
    alertCount: 9,
    activeForecastCount: 4,
    population: 1_412_000_000,
  },
  {
    id: 'iran',
    slug: 'iran',
    name: 'Iran',
    iso2: 'IR',
    iso3: 'IRN',
    region: 'middle-east',
    overallRiskScore: 82,
    riskLevel: 'high',
    riskCategories: {
      political: 76,
      military: 80,
      economic: 88,
      social: 79,
      environmental: 61,
    },
    summary:
      'Iran\'s nuclear program has advanced to near-breakout capability, generating acute proliferation concerns. The proxy network spanning Lebanon, Yemen, Iraq, and Syria remains active. Domestic unrest following the Mahsa Amini protests has been suppressed but underlying tensions persist. Economic conditions are severe due to sanctions and mismanagement.',
    keyActors: ['ali-khamenei', 'irgc'],
    capital: 'Tehran',
    lastUpdated: '2026-03-29',
    alertCount: 11,
    activeForecastCount: 3,
    population: 86_800_000,
  },
  {
    id: 'north-korea',
    slug: 'north-korea',
    name: 'North Korea',
    iso2: 'KP',
    iso3: 'PRK',
    region: 'east-asia',
    overallRiskScore: 85,
    riskLevel: 'critical',
    riskCategories: {
      political: 90,
      military: 92,
      economic: 83,
      social: 87,
      environmental: 45,
    },
    summary:
      'North Korea has continued ballistic missile tests and is assessed to possess a functional nuclear arsenal of 40-60 warheads. The Kim regime has deepened military cooperation with Russia, supplying artillery ammunition in exchange for technical assistance. No credible diplomatic pathway exists at present.',
    keyActors: ['kim-jong-un'],
    capital: 'Pyongyang',
    lastUpdated: '2026-03-27',
    alertCount: 7,
    activeForecastCount: 2,
    population: 25_900_000,
  },
  {
    id: 'taiwan',
    slug: 'taiwan',
    name: 'Taiwan',
    iso2: 'TW',
    iso3: 'TWN',
    region: 'east-asia',
    overallRiskScore: 71,
    riskLevel: 'high',
    riskCategories: {
      political: 68,
      military: 82,
      economic: 54,
      social: 42,
      environmental: 38,
    },
    summary:
      'Taiwan remains the most significant flashpoint in East Asia. PLA military exercises near Taiwan have increased in frequency and scale. The new administration has maintained a cautious position on cross-strait dialogue while strengthening defense partnerships. Semiconductor supply chain dependencies create global stakes in any conflict scenario.',
    keyActors: ['peoples-liberation-army'],
    capital: 'Taipei',
    lastUpdated: '2026-03-28',
    alertCount: 6,
    activeForecastCount: 3,
    population: 23_600_000,
  },
  {
    id: 'venezuela',
    slug: 'venezuela',
    name: 'Venezuela',
    iso2: 'VE',
    iso3: 'VEN',
    region: 'latin-america',
    overallRiskScore: 67,
    riskLevel: 'elevated',
    riskCategories: {
      political: 78,
      military: 52,
      economic: 82,
      social: 74,
      environmental: 48,
    },
    summary:
      'Venezuela remains in deep economic and humanitarian crisis under the Maduro government. The disputed 2024 election has resulted in increased international isolation. Mass emigration continues, with over 7 million Venezuelans displaced regionally. Border tensions with Guyana over the Essequibo region have escalated significantly.',
    keyActors: ['nicolas-maduro'],
    capital: 'Caracas',
    lastUpdated: '2026-03-25',
    alertCount: 5,
    activeForecastCount: 2,
    population: 28_700_000,
  },
  {
    id: 'ethiopia',
    slug: 'ethiopia',
    name: 'Ethiopia',
    iso2: 'ET',
    iso3: 'ETH',
    region: 'sub-saharan-africa',
    overallRiskScore: 74,
    riskLevel: 'high',
    riskCategories: {
      political: 72,
      military: 76,
      economic: 69,
      social: 80,
      environmental: 71,
    },
    summary:
      'Ethiopia is navigating a fragile post-Tigray conflict environment. The Pretoria peace deal has reduced large-scale fighting but implementation remains contested. Tensions in Amhara and Oromia regions continue to generate internal displacement. The country\'s bid for sea access has created friction with Eritrea and Somalia.',
    keyActors: ['abiy-ahmed'],
    capital: 'Addis Ababa',
    lastUpdated: '2026-03-26',
    alertCount: 8,
    activeForecastCount: 2,
    population: 126_500_000,
  },
  {
    id: 'israel',
    slug: 'israel',
    name: 'Israel',
    iso2: 'IL',
    iso3: 'ISR',
    region: 'middle-east',
    overallRiskScore: 80,
    riskLevel: 'high',
    riskCategories: {
      political: 77,
      military: 85,
      economic: 58,
      social: 72,
      environmental: 35,
    },
    summary:
      'Israel\'s military operations in Gaza have generated widespread international condemnation and stretched regional security dynamics. The northern front with Hezbollah remains tense following exchange of fire. Iran\'s direct missile and drone attacks in April 2024 marked a significant escalation threshold. Coalition government stability remains uncertain.',
    keyActors: ['idf', 'irgc'],
    capital: 'Jerusalem',
    lastUpdated: '2026-03-29',
    alertCount: 13,
    activeForecastCount: 4,
    population: 9_800_000,
  },
  {
    id: 'myanmar',
    slug: 'myanmar',
    name: 'Myanmar',
    iso2: 'MM',
    iso3: 'MMR',
    region: 'southeast-asia',
    overallRiskScore: 79,
    riskLevel: 'high',
    riskCategories: {
      political: 88,
      military: 82,
      economic: 76,
      social: 83,
      environmental: 52,
    },
    summary:
      'Myanmar\'s military junta faces an unprecedented coordinated resistance offensive. The Brotherhood Alliance offensive in late 2023 captured significant territory in Shan and Rakhine states. The junta has lost effective control over large portions of the country. Humanitarian conditions are catastrophic, with over 2 million internally displaced.',
    keyActors: ['tatmadaw'],
    capital: 'Naypyidaw',
    lastUpdated: '2026-03-27',
    alertCount: 9,
    activeForecastCount: 2,
    population: 54_400_000,
  },
]
