// AUTO-GENERATED by scripts/generate-country-profiles.ts — do not edit manually

export const GENERATED_ACTORS = 
[
  {
    "id": "hayat-tahrir-al-sham",
    "name": "Hayat Tahrir al-Sham (HTS)",
    "type": "non_state",
    "role": "De facto ruling faction; largest Syrian rebel group",
    "riskContribution": "high",
    "description": "HTS emerged as the dominant force in Syria's December 2024 post-Assad transition, controlling significant territory including Aleppo and Idlib provinces. The group's governance capacity and exclusion of hardline jihadist elements position it as the primary actor shaping Syria's fragile political trajectory, though concerns persist over its ideological roots and commitment to inclusivity.",
    "affiliations": [
      "Syrian rebel coalition",
      "anti-Assad forces"
    ],
    "countrySlug": "syria"
  },
  {
    "id": "kurdish-forces-syria",
    "name": "Kurdish-led Syrian Democratic Forces (SDF)",
    "type": "non_state",
    "role": "De facto autonomous authority in northeast Syria",
    "riskContribution": "high",
    "description": "The SDF controls resource-rich northeastern Syria including oil fields and maintains a quasi-autonomous administration independent of central authority. The group's ties to the PKK and Turkish security concerns create a persistent flashpoint for regional conflict and complicate post-Assad stabilization efforts.",
    "affiliations": [
      "Kurdish independence movement",
      "U.S.-backed coalition"
    ],
    "countrySlug": "syria"
  },
  {
    "id": "syrian-army-remnants",
    "name": "Syrian Armed Forces (SAF) - Remnant Factions",
    "type": "state",
    "role": "Fragmented state military apparatus; potential spoiler",
    "riskContribution": "medium",
    "description": "Remnants of Assad's military remain scattered across Syria, retaining pockets of capability and causing security vacuums in contested areas. The integration or elimination of these forces is critical to stabilization; their potential realignment with various factions presents ongoing risks to transitional authority.",
    "affiliations": [
      "Former Assad government"
    ],
    "countrySlug": "syria"
  },
  {
    "id": "mohamed-hamdan-dagalo",
    "name": "Mohamed Hamdan Dagalo (Hemedti)",
    "type": "individual",
    "role": "Commander of the Rapid Support Forces (RSF)",
    "riskContribution": "high",
    "description": "Hemedti leads the RSF, which has proven militarily competitive against the SAF despite lacking state resources. His faction's recruitment of foreign mercenaries and control of mineral-rich regions grant operational resources, making him a central driver of Sudan's civil war trajectory and potential kingmaker in any settlement.",
    "affiliations": [
      "Rapid Support Forces (RSF)",
      "Janjaweed networks"
    ],
    "countrySlug": "sudan"
  },
  {
    "id": "abdel-fattah-al-burhan",
    "name": "General Abdel Fattah al-Burhan",
    "type": "individual",
    "role": "Chief of the Sudanese Armed Forces (SAF)",
    "riskContribution": "high",
    "description": "Al-Burhan commands the state military and remains determined to reassert central authority, making the SAF-RSF conflict existential for Sudan's political future. His faction controls much of Khartoum and central Sudan but faces eroding capacity amid RSF advances and international isolation, complicating prospects for negotiated settlement.",
    "affiliations": [
      "Sudanese Armed Forces (SAF)",
      "Sudanese government"
    ],
    "countrySlug": "sudan"
  },
  {
    "id": "sudanese-government-transition",
    "name": "Sudan Transitional Authority / International Community",
    "type": "international_org",
    "role": "Mediator and humanitarian actor in civil war",
    "riskContribution": "medium",
    "description": "International bodies and the transitional civilian government lack enforcement capacity to stop the SAF-RSF conflict, yet their mediation efforts and humanitarian operations are essential to managing the catastrophic displacement crisis. Their ability to broker ceasefires remains constrained by both warring parties' maximalist positions.",
    "affiliations": [
      "United Nations",
      "African Union",
      "International partners"
    ],
    "countrySlug": "sudan"
  },
  {
    "id": "jimmy-cherizier",
    "name": "Jimmy Cherizier (Barbecue)",
    "type": "individual",
    "role": "Leader of the G9 gang federation; de facto Port-au-Prince power broker",
    "riskContribution": "high",
    "description": "Cherizier commands the largest gang coalition in Haiti, controlling critical territory and infrastructure in Port-au-Prince. His faction's capacity to disrupt security, extort commerce, and mobilize violence makes him the primary obstacle to state stabilization and a de facto veto player in any governance transition.",
    "affiliations": [
      "G9 gang federation",
      "armed gang networks"
    ],
    "countrySlug": "haiti"
  },
  {
    "id": "garry-conille",
    "name": "Garry Conille",
    "type": "individual",
    "role": "Prime Minister of Haiti",
    "riskContribution": "medium",
    "description": "Conille leads Haiti's transitional government with minimal capacity to govern outside secured zones. His administration depends entirely on the Kenyan-led security mission for operational authority, limiting his ability to implement reform or challenge entrenched gang power without external military support.",
    "affiliations": [
      "Haiti transitional government",
      "International security partners"
    ],
    "countrySlug": "haiti"
  },
  {
    "id": "kenyan-security-mission",
    "name": "Kenyan-led Multinational Security Mission (MSS)",
    "type": "international_org",
    "role": "Foreign military stabilization force; de facto security guarantor",
    "riskContribution": "high",
    "description": "The Kenya-led MSS provides the only significant armed force capable of countering gang control in Port-au-Prince and represents Haiti's best near-term security stabilization option. Its mandate, funding constraints, and timeline remain contentious; withdrawal without institutional replacement could trigger rapid state collapse and renewed gang dominance.",
    "affiliations": [
      "United Nations",
      "Kenya",
      "multinational partners"
    ],
    "countrySlug": "haiti"
  },
  {
    "id": "al-shabaab-somalia",
    "name": "Al-Shabaab",
    "type": "non_state",
    "role": "Designated terrorist organization; de facto authority in rural areas",
    "riskContribution": "high",
    "description": "Al-Qaeda-affiliated insurgent group controlling significant rural territory across southern and central Somalia. Conducts regular coordinated attacks in Mogadishu and controls taxation, judicial systems, and military recruitment in contested areas. Primary driver of insecurity and destabilization across the Horn of Africa.",
    "affiliations": [
      "Al-Qaeda",
      "Al-Qaeda in the Islamic Maghreb"
    ],
    "countrySlug": "somalia"
  },
  {
    "id": "hassan-sheikh-mohamud",
    "name": "Hassan Sheikh Mohamud",
    "type": "individual",
    "role": "President of Somalia (since 2022)",
    "riskContribution": "medium",
    "description": "Elected president overseeing weak federal government with limited territorial control and capacity. Efforts to centralize authority face resistance from autonomous regional administrations and clan-based militias. Dependent on international military support and external legitimacy.",
    "affiliations": [
      "Federal Government of Somalia",
      "African Union"
    ],
    "countrySlug": "somalia"
  },
  {
    "id": "somaliland-govt",
    "name": "Somaliland Government",
    "type": "state",
    "role": "De facto autonomous regional authority; contested separatist entity",
    "riskContribution": "medium",
    "description": "Self-declared independent state in northern Somalia with functional governance structures but no international recognition. Emergence as de facto state fragments national authority and complicates federal state-building efforts. Maintains separate security apparatus and administrative institutions.",
    "affiliations": [
      "Somaliland Armed Forces"
    ],
    "countrySlug": "somalia"
  },
  {
    "id": "shehbaz-sharif",
    "name": "Muhammad Shehbaz Sharif",
    "type": "individual",
    "role": "Prime Minister of Pakistan",
    "riskContribution": "medium",
    "description": "Current PM navigating acute economic crisis and political fragmentation. His government faces pressure from both Imran Khan's imprisoned faction and military influence, complicating governance and reform efforts critical to Pakistan's stability.",
    "affiliations": [
      "Pakistan Muslim League",
      "Government of Pakistan"
    ],
    "countrySlug": "pakistan"
  },
  {
    "id": "tehrik-i-taliban-pakistan",
    "name": "Tehrik-i-Taliban Pakistan (TTP)",
    "type": "non_state",
    "role": "Militant insurgency",
    "riskContribution": "high",
    "description": "Resurgent militant group conducting sustained attacks across Khyber Pakhtunkhwa and urban centers. TTP's renewed capacity poses direct threat to civilian infrastructure, military installations, and regional stability, with potential to destabilize nuclear-armed state.",
    "affiliations": [
      "Taliban (ideological alignment)",
      "Al-Qaeda (loose coordination)"
    ],
    "countrySlug": "pakistan"
  },
  {
    "id": "general-asim-munir",
    "name": "General Asim Munir",
    "type": "individual",
    "role": "Chief of Army Staff",
    "riskContribution": "high",
    "description": "Pakistan's military leader and de facto power broker. Controls nuclear arsenal and security apparatus; his decisions on civil-military balance, Imran Khan detention, and counter-insurgency strategy fundamentally shape Pakistan's political trajectory and regional posture.",
    "affiliations": [
      "Pakistan Army",
      "Military establishment"
    ],
    "countrySlug": "pakistan"
  },
  {
    "id": "abdul-hamid-dbeibah",
    "name": "Abdul Hamid Dbeibah",
    "type": "individual",
    "role": "Prime Minister of Government of National Unity (GNU)",
    "riskContribution": "medium",
    "description": "Head of internationally-recognized Tripoli government facing delegitimacy from LNA rival faction and dependence on Turkish and Qatari military backing. His authority is confined to western Libya amid fragmentation, limiting state capacity.",
    "affiliations": [
      "Government of National Unity (GNU)",
      "Libya government"
    ],
    "countrySlug": "libya"
  },
  {
    "id": "khalifa-haftar",
    "name": "Khalifa Haftar",
    "type": "individual",
    "role": "Commander, Libyan National Army (LNA)",
    "riskContribution": "high",
    "description": "Eastern Libya's military strongman controlling the LNA and backed by UAE, Egypt, and Russian Wagner forces. Haftar's refusal to recognize GNU and control of oil-rich eastern territory perpetuates state partition and foreign military entanglement.",
    "affiliations": [
      "Libyan National Army (LNA)",
      "UAE",
      "Egypt",
      "Russia/Wagner"
    ],
    "countrySlug": "libya"
  },
  {
    "id": "turkish-military-libya",
    "name": "Turkish Military Operations (Libya)",
    "type": "state",
    "role": "Foreign military backer of GNU",
    "riskContribution": "high",
    "description": "Turkey's sustained military and drone support to Tripoli-based GNU shapes the conflict's trajectory and prevents LNA victory, while anchoring Libya in regional Turkish-Emirati competition. Turkish presence entrenches external dependency and complicates settlement prospects.",
    "affiliations": [
      "Turkey (Government)",
      "NATO"
    ],
    "countrySlug": "libya"
  },
  {
    "id": "muhammad-al-sudani",
    "name": "Muhammad Shia al-Sudani",
    "type": "individual",
    "role": "Prime Minister of Iraq",
    "riskContribution": "medium",
    "description": "Iraqi PM nominally leading Baghdad government but constrained by Iran-backed militia dominance and U.S. military presence. His authority over security forces is limited, rendering governance reform and anti-corruption efforts largely symbolic.",
    "affiliations": [
      "Iraqi government",
      "Shia political coalition"
    ],
    "countrySlug": "iraq"
  },
  {
    "id": "popular-mobilization-forces",
    "name": "Popular Mobilization Forces (PMF)",
    "type": "non_state",
    "role": "Iranian-backed militia umbrella",
    "riskContribution": "high",
    "description": "Loose coalition of Shia militias deeply integrated into Iraqi security apparatus and directly subordinate to Iran's IRGC. PMF groups conduct regular attacks on U.S. personnel, undermine state monopoly on force, and entrench Iranian influence over Iraqi governance.",
    "affiliations": [
      "Iran (IRGC)",
      "Iraqi state (nominal integration)"
    ],
    "countrySlug": "iraq"
  },
  {
    "id": "isis-iraq",
    "name": "Islamic State (ISIS/ISIL)",
    "type": "non_state",
    "role": "Insurgent terrorist organization",
    "riskContribution": "high",
    "description": "Degraded but operationally capable terrorist group maintaining cells and insurgent networks across Iraq. ISIS conducts periodic attacks on civilians, military, and infrastructure; their resurrection risk remains acute if security pressure eases or sectarian tensions spike.",
    "affiliations": [],
    "countrySlug": "iraq"
  },
  {
    "id": "assimi-goita",
    "name": "Assimi Goïta",
    "type": "individual",
    "role": "Colonel, Military Junta Leader",
    "riskContribution": "high",
    "description": "Leader of Mali's military junta since 2020 coup; consolidated power through successive consolidations and expelled Western military presence. His governance and alignment with Russian interests have fundamentally reoriented Mali's geopolitical posture while jihadist violence continues unabated.",
    "affiliations": [
      "Mali Military Junta",
      "CNRTP"
    ],
    "countrySlug": "mali"
  },
  {
    "id": "group-for-sahel-support-islam",
    "name": "Group for the Support of Islam and Muslims (JNIM)",
    "type": "non_state",
    "role": "Jihadist Insurgent Coalition",
    "riskContribution": "high",
    "description": "Al-Qaeda-affiliated jihadist coalition controlling significant Sahel territory and conducting sustained insurgent operations across Mali. JNIM's expanded territorial control and recruitment represent a primary driver of Mali's instability and humanitarian crisis.",
    "affiliations": [
      "Al-Qaeda in the Islamic Maghreb (AQIM)"
    ],
    "countrySlug": "mali"
  },
  {
    "id": "wagner-mali",
    "name": "Wagner Group (Mali Operations)",
    "type": "non_state",
    "role": "Russian Mercenary Force",
    "riskContribution": "high",
    "description": "Russian private military force contracted by Mali's junta following French expulsion; provides counterinsurgency support and reinforces Russian strategic influence in West Africa. Wagner's presence reflects deepening Russia-Mali ties and complicates international oversight.",
    "affiliations": [
      "Russia",
      "Yevgeny Prigozhin network"
    ],
    "countrySlug": "mali"
  },
  {
    "id": "abdourahamane-tchiani",
    "name": "Abdourahamane Tchiani",
    "type": "individual",
    "role": "General, Military Junta Leader",
    "riskContribution": "high",
    "description": "Leader of Niger's National Council for the Safeguard of the Homeland (CNSP) following the July 2023 coup; orchestrated expulsion of French and U.S. military presence and signaled openness to Russian engagement. His junta consolidation directly impacts Sahel regional stability.",
    "affiliations": [
      "Niger Military Junta",
      "CNSP"
    ],
    "countrySlug": "niger"
  },
  {
    "id": "islamic-state-west-africa",
    "name": "Islamic State West Africa Province (ISWAP)",
    "type": "non_state",
    "role": "Jihadist Insurgent Group",
    "riskContribution": "high",
    "description": "ISIS-affiliated jihadist faction expanding territorial control in Niger's Tillabéri and Tahoua regions through coordinated insurgent attacks. ISWAP's operational expansion and sectarian violence represent a critical driver of Niger's humanitarian and security crisis.",
    "affiliations": [
      "Islamic State"
    ],
    "countrySlug": "niger"
  },
  {
    "id": "niger-french-military",
    "name": "French Military Presence (Expulsion)",
    "type": "state",
    "role": "Western Military Force (Expelled)",
    "riskContribution": "medium",
    "description": "France maintained significant military basing and counterterrorism operations in Niger until junta expulsion in 2023. The withdrawal of French forces removed a key Western counterbalance and created a security vacuum that jihadist groups are exploiting.",
    "affiliations": [
      "France",
      "NATO"
    ],
    "countrySlug": "niger"
  },
  {
    "id": "ibrahim-traore",
    "name": "Ibrahim Traoré",
    "type": "individual",
    "role": "Captain, Military Junta Leader",
    "riskContribution": "high",
    "description": "Leader of Burkina Faso's junta following successive coups in 2022; appointed himself president and pursued aggressive anti-French and pro-Russian alignment while expanding military operations against jihadists. Traoré's populist rhetoric masks deepening jihadist territorial losses and humanitarian costs.",
    "affiliations": [
      "Burkina Faso Military Junta",
      "MPSR"
    ],
    "countrySlug": "burkina-faso"
  },
  {
    "id": "islamic-state-sahel",
    "name": "Islamic State Sahel Province (ISSP)",
    "type": "non_state",
    "role": "Jihadist Insurgent Group",
    "riskContribution": "high",
    "description": "ISIS-affiliated jihadist faction controlling significant territory in Burkina Faso's North and East regions; conducts sustained attacks on military and civilian targets. ISSP's territorial expansion and operational sophistication represent the primary destabilizing force in Burkina Faso.",
    "affiliations": [
      "Islamic State"
    ],
    "countrySlug": "burkina-faso"
  },
  {
    "id": "burkina-russian-alignment",
    "name": "Russian Military Advisors and Wagner",
    "type": "state",
    "role": "Russian Strategic Presence",
    "riskContribution": "medium",
    "description": "Russian military advisors and private contractors expanded presence in Burkina Faso following French expulsion; provide counterinsurgency training and reinforce Moscow's West African influence. Russian engagement reflects broader geopolitical competition and complicates Western stabilization efforts.",
    "affiliations": [
      "Russia"
    ],
    "countrySlug": "burkina-faso"
  },
  {
    "id": "umaro-sissoco-embalo",
    "name": "Umaro Sissoco Embalo",
    "type": "individual",
    "role": "President of Guinea-Bissau",
    "riskContribution": "high",
    "description": "President since 2020 with a contested election and history of military involvement. His consolidation of power and control over security apparatus directly shapes Guinea-Bissau's institutional stability and vulnerability to state capture.",
    "affiliations": [
      "Guinea-Bissau Government",
      "Military establishment"
    ],
    "countrySlug": "guinea-bissau"
  },
  {
    "id": "guinea-bissau-military",
    "name": "Guinea-Bissau Armed Forces (FAB)",
    "type": "state",
    "role": "National military establishment",
    "riskContribution": "high",
    "description": "Historically fragmented military with repeated coup attempts and factional tensions. The FAB remains weakly institutionalized and susceptible to politicization, directly threatening constitutional order and enabling narcotics trafficking networks.",
    "affiliations": [
      "Guinea-Bissau Government"
    ],
    "countrySlug": "guinea-bissau"
  },
  {
    "id": "guinea-bissau-narco-networks",
    "name": "Transnational Drug Trafficking Networks",
    "type": "non_state",
    "role": "Organized crime syndicates",
    "riskContribution": "high",
    "description": "West African cocaine transit hubs exploit Guinea-Bissau's weak border controls and corrupt institutions. These networks corrupt state officials, destabilize governance, and finance armed factions, making the country a strategic node in Latin American-to-European drug flows.",
    "affiliations": [
      "International criminal organizations",
      "Corrupt state actors"
    ],
    "countrySlug": "guinea-bissau"
  },
  {
    "id": "farc-dissidents",
    "name": "FARC Dissident Groups",
    "type": "non_state",
    "role": "Armed insurgent faction",
    "riskContribution": "high",
    "description": "Splinter factions of the FARC that rejected the 2016 peace agreement, primarily operating in southern Colombia. These groups maintain control over coca cultivation and trafficking routes, directly undermining peace implementation and fueling rural violence.",
    "affiliations": [
      "drug trafficking networks",
      "illegal armed groups"
    ],
    "countrySlug": "colombia"
  },
  {
    "id": "eln-colombia",
    "name": "National Liberation Army (ELN)",
    "type": "non_state",
    "role": "Guerrilla organization",
    "riskContribution": "high",
    "description": "Colombia's largest remaining guerrilla group actively engaged in peace negotiations with the government. The ELN controls significant territory in border regions and maintains revenue streams through extortion, kidnapping, and drug trafficking, making peace talks fragile.",
    "affiliations": [
      "guerrilla movements",
      "drug trafficking"
    ],
    "countrySlug": "colombia"
  },
  {
    "id": "gustavo-petro",
    "name": "Gustavo Petro",
    "type": "individual",
    "role": "President of Colombia",
    "riskContribution": "medium",
    "description": "Colombia's first left-wing president (inaugurated 2022) pursuing ambitious peace negotiations with ELN and addressing rural inequality. His administration's capacity to deliver on peace commitments and manage FARC dissident activity remains critical to Colombia's stability trajectory.",
    "affiliations": [
      "Colombian government",
      "left-wing political movement"
    ],
    "countrySlug": "colombia"
  },
  {
    "id": "sinaloa-cartel",
    "name": "Sinaloa Cartel",
    "type": "non_state",
    "role": "Drug trafficking organization",
    "riskContribution": "high",
    "description": "Mexico's historically dominant drug trafficking organization with deep institutional integration into state and local governance structures. Leadership fragmentation following recent arrests of key figures has intensified cartel violence and competition with rivals for territorial control.",
    "affiliations": [
      "drug trafficking networks",
      "organized crime"
    ],
    "countrySlug": "mexico"
  },
  {
    "id": "jalisco-cartel",
    "name": "Jalisco New Generation Cartel (CJNG)",
    "type": "non_state",
    "role": "Criminal organization",
    "riskContribution": "high",
    "description": "Mexico's fastest-growing cartel with expanding territorial footprint and increasingly sophisticated operations across multiple Mexican states and Central America. The CJNG's challenge to state authority and involvement in mass violence represents a primary driver of Mexico's elevated risk profile.",
    "affiliations": [
      "drug trafficking networks",
      "organized crime",
      "fentanyl networks"
    ],
    "countrySlug": "mexico"
  },
  {
    "id": "claudia-sheinbaum",
    "name": "Claudia Sheinbaum",
    "type": "individual",
    "role": "President of Mexico",
    "riskContribution": "medium",
    "description": "Mexico's first female president (inaugurated 2024) inheriting a cartel violence crisis with historically elevated homicide rates. Her administration's 'Hugs Not Bullets' security strategy and capacity to constrain cartel expansion remain central to Mexico's near-term stability outlook.",
    "affiliations": [
      "Mexican government",
      "Morena party"
    ],
    "countrySlug": "mexico"
  },
  {
    "id": "abdel-fattah-el-sisi",
    "name": "Abdel Fattah El-Sisi",
    "type": "individual",
    "role": "President of Egypt",
    "riskContribution": "high",
    "description": "Egypt's dominant political figure maintaining tight centralized control through military and security apparatus. Sisi's management of economic crisis, Sinai insurgency, and suppression of political dissent directly shapes Egypt's governance capacity and strategic alignment with regional and international powers.",
    "affiliations": [
      "Egyptian government",
      "Egyptian military"
    ],
    "countrySlug": "egypt"
  },
  {
    "id": "isis-sinai",
    "name": "Islamic State – Sinai Province (ISKP)",
    "type": "non_state",
    "role": "Militant insurgent organization",
    "riskContribution": "high",
    "description": "ISIS-affiliated insurgency controlling significant territory in Egypt's North Sinai Peninsula and conducting sustained asymmetric warfare against military and civilian targets. The group exploits ungoverned spaces and local grievances to perpetuate a protracted conflict that strains state resources.",
    "affiliations": [
      "Islamic State",
      "jihadist networks",
      "terrorist organizations"
    ],
    "countrySlug": "egypt"
  },
  {
    "id": "egyptian-military",
    "name": "Egyptian Armed Forces",
    "type": "state",
    "role": "National military institution",
    "riskContribution": "medium",
    "description": "Egypt's primary state security institution under presidential command, central to Sisi's power consolidation and counterinsurgency operations in Sinai. The military's institutional interests in budget allocation and territorial control significantly influence both domestic politics and Egypt's regional strategic posture.",
    "affiliations": [
      "Egyptian state",
      "government"
    ],
    "countrySlug": "egypt"
  },
  {
    "id": "kassym-jomart-tokayev",
    "name": "Kassym-Jomart Tokayev",
    "type": "individual",
    "role": "President of Kazakhstan",
    "riskContribution": "high",
    "description": "Kazakhstan's president since 2019, balancing Moscow's security demands with Western energy interests and regional stability. His government's response to domestic unrest and resource management directly impacts Central Asian geopolitical alignment.",
    "affiliations": [
      "Kazakhstan Government",
      "Eurasian Economic Union"
    ],
    "countrySlug": "kazakhstan"
  },
  {
    "id": "kazakhstan-security-forces",
    "name": "Kazakhstan Security Forces (National Security Committee & Internal Troops)",
    "type": "state",
    "role": "Internal security and military apparatus",
    "riskContribution": "high",
    "description": "The KNB and Internal Troops represent the state monopoly on coercive force and primary tool for regime stability. Recent protests revealed their operational reach and willingness to use force against civilian demonstrations.",
    "affiliations": [
      "Kazakhstan Government"
    ],
    "countrySlug": "kazakhstan"
  },
  {
    "id": "mangystau-regional-networks",
    "name": "Mangystau Regional Opposition Networks",
    "type": "non_state",
    "role": "Localized civil resistance and labor organizing",
    "riskContribution": "medium",
    "description": "Worker and activist networks in Mangystau region around oil and gas production have mobilized repeatedly against state policies and economic marginalization. Their capacity to trigger cascading unrest poses an internal stability risk.",
    "affiliations": [
      "Labor movements",
      "Regional civic organizations"
    ],
    "countrySlug": "kazakhstan"
  },
  {
    "id": "alexander-lukashenko",
    "name": "Alexander Lukashenko",
    "type": "individual",
    "role": "President of Belarus",
    "riskContribution": "high",
    "description": "Authoritarian leader since 1994, functionally a Russian vassal since 2022 invasion of Ukraine. His dependence on Moscow for economic survival and security guarantees makes him a key vector for Russian regional influence and military operations.",
    "affiliations": [
      "Belarus Government",
      "Russia",
      "Eurasian Economic Union"
    ],
    "countrySlug": "belarus"
  },
  {
    "id": "belarusian-security-apparatus",
    "name": "Belarusian Security Apparatus (KGB, Interior Ministry)",
    "type": "state",
    "role": "Internal repression and state control",
    "riskContribution": "high",
    "description": "The KGB and Interior Ministry enforce Lukashenko's authoritarian rule through mass surveillance and arbitrary detention of opposition figures. Their integration with Russian security services amplifies regional destabilization risk.",
    "affiliations": [
      "Belarus Government",
      "Russia"
    ],
    "countrySlug": "belarus"
  },
  {
    "id": "belarusian-opposition-in-exile",
    "name": "Belarusian Opposition in Exile (Sviatlana Tsikhanouskaya & Coordination Council)",
    "type": "non_state",
    "role": "Exiled democratic opposition leadership",
    "riskContribution": "low",
    "description": "Exiled opposition leader and coalition operate from Poland and Lithuania, maintaining diplomatic and informational pressure on Lukashenko's regime. While externally marginalized, they represent the latent mobilization potential within Belarus.",
    "affiliations": [
      "Democratic opposition",
      "Western governments",
      "Belarusian diaspora"
    ],
    "countrySlug": "belarus"
  },
  {
    "id": "mamady-doumbouya",
    "name": "Mamady Doumbouya",
    "type": "individual",
    "role": "Military Leader and Head of Transition Government",
    "riskContribution": "high",
    "description": "Colonel leading Guinea's military junta since the 2021 coup, currently managing the transition toward civilian rule. His influence over timing and conditions of democratization and his relationships with external actors directly shape Guinea's institutional trajectory.",
    "affiliations": [
      "Guinea Armed Forces",
      "Transitional government"
    ],
    "countrySlug": "guinea"
  },
  {
    "id": "guinea-armed-forces",
    "name": "Guinea Armed Forces (Military Junta Factions)",
    "type": "state",
    "role": "Military rulers and power brokers",
    "riskContribution": "high",
    "description": "The armed forces remain factionally divided over transition timelines and resource distribution. Internal military cohesion is a critical variable for Guinea's stability; fragmentation could trigger renewed instability or competing power centers.",
    "affiliations": [
      "Guinea Government",
      "Regional militaries"
    ],
    "countrySlug": "guinea"
  },
  {
    "id": "guinea-bauxite-mining-interests",
    "name": "Guinea Bauxite Mining Sector (International & Domestic Actors)",
    "type": "non_state",
    "role": "Economic power brokers and resource competition",
    "riskContribution": "medium",
    "description": "Guinea's vast bauxite reserves attract Chinese, Russian, and Western corporate interests alongside domestic commercial networks. Competition for mining concessions and revenue control directly fuels elite faction-building and corruption-driven instability.",
    "affiliations": [
      "International mining corporations",
      "Domestic commercial networks",
      "Chinese interests",
      "Russian interests"
    ],
    "countrySlug": "guinea"
  },
  {
    "id": "mahamat-idriss-deby-itno",
    "name": "Mahamat Idriss Déby Itno",
    "type": "individual",
    "role": "Head of State & Military Junta Leader",
    "riskContribution": "high",
    "description": "Military leader who took control after his father's death in 2021, heading the Transitional Sovereignty Council. His consolidation of power through delayed elections and military governance has intensified political instability and democratic backsliding in Chad, critical given the country's regional counterterrorism role.",
    "affiliations": [
      "Transitional Sovereignty Council",
      "Chadian Armed Forces"
    ],
    "countrySlug": "chad"
  },
  {
    "id": "wakit-taba-movement",
    "name": "WAKIT TABA Movement",
    "type": "non_state",
    "role": "Opposition Coalition & Protest Movement",
    "riskContribution": "medium",
    "description": "Broad civilian opposition coalition mobilizing against military rule and demanding democratic transition. Their sustained anti-government activism and periodic demonstrations create social friction and potential for escalation, complicating governance stability.",
    "affiliations": [
      "Civil society",
      "Opposition parties"
    ],
    "countrySlug": "chad"
  },
  {
    "id": "boko-haram-jais",
    "name": "Boko Haram & Jais (Islamic State West Africa Province)",
    "type": "non_state",
    "role": "Terrorist/Insurgent Groups",
    "riskContribution": "high",
    "description": "Active terrorist networks operating in Lake Chad region, conducting cross-border attacks against Chadian military and civilians. Their persistent insurgency drains state resources and undermines Chad's stability, particularly in the Sahel.",
    "affiliations": [
      "Islamic State",
      "Transnational terrorist networks"
    ],
    "countrySlug": "chad"
  },
  {
    "id": "filipe-nyusi",
    "name": "Filipe Nyusi",
    "type": "individual",
    "role": "Former President & Political Opposition",
    "riskContribution": "medium",
    "description": "Former head of state (2015–2024) representing significant opposition faction within Frelimo party and broader political landscape. His contested electoral loss and ongoing political positioning contribute to power struggles and factional tensions within Mozambique's ruling establishment.",
    "affiliations": [
      "FRELIMO",
      "Mozambican political elite"
    ],
    "countrySlug": "mozambique"
  },
  {
    "id": "daniel-chapo",
    "name": "Daniel Chapo",
    "type": "individual",
    "role": "Opposition Leader & Presidential Challenger",
    "riskContribution": "high",
    "description": "Charismatic opposition politician who secured significant support in 2024 elections, catalyzing unprecedented civil unrest and protests against alleged electoral fraud. His mobilization of youth-driven opposition represents a critical destabilizing force challenging state legitimacy.",
    "affiliations": [
      "Podemos",
      "Civil society movements"
    ],
    "countrySlug": "mozambique"
  },
  {
    "id": "renamo-armed-resistance",
    "name": "RENAMO Armed Wing & Dissident Elements",
    "type": "non_state",
    "role": "Opposition Armed Actors",
    "riskContribution": "high",
    "description": "Insurgent factions linked to opposition RENAMO party conducting armed attacks in central Mozambique, exploiting post-electoral tensions and weak state capacity. Their resurgence threatens civilian security and military cohesion across multiple provinces.",
    "affiliations": [
      "RENAMO",
      "Armed opposition networks"
    ],
    "countrySlug": "mozambique"
  },
  {
    "id": "emmerson-mnangagwa",
    "name": "Emmerson Mnangagwa",
    "type": "individual",
    "role": "President & ZANU-PF Leader",
    "riskContribution": "high",
    "description": "Authoritarian leader ruling through military-backed ZANU-PF party since 2017, employing repression against opposition and civil society. His regime's institutional brittleness, economic collapse, and reliance on state security forces create sustained instability and human rights abuses.",
    "affiliations": [
      "ZANU-PF",
      "Zimbabwe Defence Forces"
    ],
    "countrySlug": "zimbabwe"
  },
  {
    "id": "nelson-chamisa",
    "name": "Nelson Chamisa",
    "type": "individual",
    "role": "Opposition Leader & Civil Rights Advocate",
    "riskContribution": "medium",
    "description": "Primary opposition figure leading MDC Alliance against ZANU-PF autocracy, mobilizing pro-democracy constituencies and advocating democratic reform. His electoral challenges and detention risks exemplify regime repression and fuel ongoing political tensions.",
    "affiliations": [
      "MDC Alliance",
      "Opposition coalition"
    ],
    "countrySlug": "zimbabwe"
  },
  {
    "id": "zimbabwe-defence-forces",
    "name": "Zimbabwe Defence Forces (ZDF)",
    "type": "state",
    "role": "Military Institution & State Coercive Apparatus",
    "riskContribution": "high",
    "description": "Armed forces serving as critical pillar of ZANU-PF regime, deployed extensively for internal repression and election enforcement. Their institutional autonomy from civilian oversight and historical interventions in politics constitute a primary driver of authoritarian stability and state violence.",
    "affiliations": [
      "ZANU-PF",
      "Mnangagwa regime"
    ],
    "countrySlug": "zimbabwe"
  },
  {
    "id": "daniel-ortega",
    "name": "Daniel Ortega",
    "type": "individual",
    "role": "President of Nicaragua",
    "riskContribution": "high",
    "description": "Autocratic leader consolidating power through constitutional amendments and repression of opposition. His regime's alliance with authoritarian actors (Russia, China, Iran) and suppression of democratic institutions elevates regional instability and draws U.S. strategic concern.",
    "affiliations": [
      "Sandinista National Liberation Front (FSLN)",
      "Russia",
      "China",
      "Iran"
    ],
    "countrySlug": "nicaragua"
  },
  {
    "id": "nicaraguan-national-police",
    "name": "Nicaraguan National Police (PNN)",
    "type": "state",
    "role": "Domestic Security Force",
    "riskContribution": "high",
    "description": "State security apparatus under Ortega's direct control; used for political repression, intimidation, and arrest of opposition figures. Functions as enforcement mechanism for authoritarian consolidation rather than rule-of-law institution.",
    "affiliations": [
      "Daniel Ortega",
      "FSLN"
    ],
    "countrySlug": "nicaragua"
  },
  {
    "id": "nicaraguan-army",
    "name": "Nicaraguan Armed Forces (ENN)",
    "type": "state",
    "role": "Military Institution",
    "riskContribution": "medium",
    "description": "Military apparatus increasingly aligned with executive authority and foreign adversaries. Modernization efforts supported by Russia and China signal potential shift in Central American military balance and U.S. influence.",
    "affiliations": [
      "Daniel Ortega",
      "Russia",
      "China"
    ],
    "countrySlug": "nicaragua"
  },
  {
    "id": "salome-zourabichvili",
    "name": "Salome Zourabichvili",
    "type": "individual",
    "role": "President of Georgia",
    "riskContribution": "medium",
    "description": "President overseeing Georgia's precarious geopolitical position between NATO/EU alignment and Russian pressure, particularly following the contested October 2024 elections. Her administration navigates existential security concerns related to occupied territories (South Ossetia, Abkhazia) while managing domestic political instability.",
    "affiliations": [
      "Georgian Government",
      "Pro-Western Bloc"
    ],
    "countrySlug": "georgia"
  },
  {
    "id": "russia-military-command-georgia",
    "name": "Russian Military Command (South Ossetia & Abkhazia)",
    "type": "state",
    "role": "De facto occupation authority",
    "riskContribution": "high",
    "description": "Russian armed forces maintain control of Georgia's occupied territories through proxy militias and direct deployment. This occupation perpetuates the primary driver of Georgia's security crisis and constrains its NATO integration, representing a persistent flashpoint for regional escalation.",
    "affiliations": [
      "Russian Federation",
      "South Ossetian de facto authorities",
      "Abkhazian de facto authorities"
    ],
    "countrySlug": "georgia"
  },
  {
    "id": "georgian-dream-party",
    "name": "Georgian Dream Political Party",
    "type": "non_state",
    "role": "Ruling political coalition",
    "riskContribution": "high",
    "description": "Dominant ruling party with control of parliament and executive, yet increasingly polarized from opposition and civil society over democratic backsliding concerns. Its domestic political conflict with pro-Western factions creates internal instability that complicates coherent security policy amid Russian pressure.",
    "affiliations": [
      "Georgian Government"
    ],
    "countrySlug": "georgia"
  },
  {
    "id": "maia-sandu",
    "name": "Maia Sandu",
    "type": "individual",
    "role": "President of Moldova",
    "riskContribution": "medium",
    "description": "Pro-Western president navigating Moldova's existential vulnerability between EU/NATO alignment and Russian military presence in Transnistria. Her administration faces sustained Russian hybrid warfare, disinformation, and economic coercion designed to destabilize westward integration efforts.",
    "affiliations": [
      "Moldovan Government",
      "Pro-EU/NATO Bloc"
    ],
    "countrySlug": "moldova"
  },
  {
    "id": "transnistrian-separatist-authorities",
    "name": "Transnistrian Separatist Authorities",
    "type": "non_state",
    "role": "De facto breakaway regional government",
    "riskContribution": "high",
    "description": "Russian-backed separatist enclave controlling Moldova's eastern bank of the Dniester River, hosting approximately 1,500 Russian troops. Transnistria functions as a Russian military staging ground and sanctions-evasion hub, directly threatening Moldova's sovereignty and territorial integrity.",
    "affiliations": [
      "Russian Federation",
      "Breakaway separatist movement"
    ],
    "countrySlug": "moldova"
  },
  {
    "id": "vladimir-plahotniuc",
    "name": "Vladimir Plahotniuc",
    "type": "individual",
    "role": "Oligarch & political power broker",
    "riskContribution": "medium",
    "description": "Influential oligarch whose financial networks and political influence shape Moldova's internal power dynamics, governance capacity, and foreign policy direction. His activities exemplify broader state capture dynamics that weaken institutional resilience against Russian interference.",
    "affiliations": [
      "Democratic Party of Moldova",
      "Moldovan Business Establishment"
    ],
    "countrySlug": "moldova"
  },
  {
    "id": "nikol-pashinyan",
    "name": "Nikol Pashinyan",
    "type": "individual",
    "role": "Prime Minister of Armenia",
    "riskContribution": "high",
    "description": "Prime Minister facing intense domestic criticism over Armenia's 2023 territorial losses in Nagorno-Karabakh and perceived security failures. His government navigates the aftermath of military defeat while managing Russian alliance constraints and attempting incremental regional normalisation with Azerbaijan.",
    "affiliations": [
      "Armenian Government",
      "Russian-led CSTO"
    ],
    "countrySlug": "armenia"
  },
  {
    "id": "azerbaijan-military-command",
    "name": "Azerbaijani Armed Forces & Ilham Aliyev Government",
    "type": "state",
    "role": "Regional military superior power",
    "riskContribution": "high",
    "description": "Azerbaijan's military demonstrated decisive operational superiority in 2023, capturing Nagorno-Karabakh and significantly altering the regional balance. Baku's continued military buildup and control of newly captured territories creates persistent destabilization risk and potential for renewed conflict escalation against Armenia.",
    "affiliations": [
      "Republic of Azerbaijan",
      "Turkish-Azerbaijani Alliance"
    ],
    "countrySlug": "armenia"
  },
  {
    "id": "armenian-opposition-movements",
    "name": "Armenian Opposition & Civic Movements",
    "type": "non_state",
    "role": "Domestic dissent & security pressure",
    "riskContribution": "medium",
    "description": "Growing opposition to Pashinyan's government over territorial concessions and military failures, combined with broader civic mobilization for accountability and governance reform. Internal political instability constrains Armenia's capacity to respond cohesively to security threats and may trigger regime change dynamics.",
    "affiliations": [
      "Opposition political parties",
      "Civil society groups"
    ],
    "countrySlug": "armenia"
  },
  {
    "id": "ilham-aliyev",
    "name": "Ilham Aliyev",
    "type": "individual",
    "role": "President of Azerbaijan",
    "riskContribution": "high",
    "description": "Autocratic leader since 2003 driving aggressive territorial ambitions against Armenia and maintaining tight control over state institutions. His decision-making directly shapes Azerbaijan's military strategy and regional security posture, particularly regarding Nagorno-Karabakh disputes and energy leverage.",
    "affiliations": [
      "Government of Azerbaijan",
      "New Azerbaijan Party"
    ],
    "countrySlug": "azerbaijan"
  },
  {
    "id": "azerbaijan-military-general-staff",
    "name": "Azerbaijan Military General Staff",
    "type": "state",
    "role": "Armed Forces Leadership",
    "riskContribution": "high",
    "description": "Command structure overseeing military modernization and offensive operations against Armenian forces. Recent wars (2020, 2022) demonstrate institutionalized capacity for sustained combat and escalation, with Turkish support enabling advanced drone and conventional warfare capabilities.",
    "affiliations": [
      "Government of Azerbaijan"
    ],
    "countrySlug": "azerbaijan"
  },
  {
    "id": "azerbaijan-state-security-service",
    "name": "State Security Service (ADA)",
    "type": "state",
    "role": "Domestic Intelligence & Security",
    "riskContribution": "medium",
    "description": "Primary intelligence apparatus exercising broad surveillance and repression domestically while supporting military operations. Functions as key enforcer of regime control and information dominance in conflict zones.",
    "affiliations": [
      "Government of Azerbaijan"
    ],
    "countrySlug": "azerbaijan"
  },
  {
    "id": "thongloun-sisoulith",
    "name": "Thongloun Sisoulith",
    "type": "individual",
    "role": "Prime Minister of Laos",
    "riskContribution": "high",
    "description": "Current Prime Minister since 2020, representing continuity of Communist Party control. His administration maintains tight state control while navigating China's growing economic and strategic influence in Laos, a critical Belt and Road Initiative hub.",
    "affiliations": [
      "Lao People's Revolutionary Party",
      "Laotian Government"
    ],
    "countrySlug": "laos"
  },
  {
    "id": "lao-peoples-revolutionary-party",
    "name": "Lao People's Revolutionary Party (LPRP)",
    "type": "state",
    "role": "Ruling Communist Party",
    "riskContribution": "high",
    "description": "Sole political authority in Laos exercising monopoly control over state institutions and security apparatus. The party's alignment with Beijing creates systemic vulnerabilities to Chinese pressure and limits capacity for independent policy, raising stability concerns.",
    "affiliations": [
      "Communist International",
      "Chinese Communist Party"
    ],
    "countrySlug": "laos"
  },
  {
    "id": "laotian-armed-forces",
    "name": "Laotian People's Armed Forces (LPAF)",
    "type": "state",
    "role": "National Military & Security Force",
    "riskContribution": "medium",
    "description": "Primary armed force loyal to the LPRP, increasingly modernized with Chinese equipment and training. Plays central role in internal security and border enforcement, though limited capacity constrains ability to counter non-state threats effectively.",
    "affiliations": [
      "Lao People's Revolutionary Party"
    ],
    "countrySlug": "laos"
  },
  {
    "id": "mohamed-ould-ghazouani",
    "name": "Mohamed Ould Ghazouani",
    "type": "individual",
    "role": "President of Mauritania",
    "riskContribution": "high",
    "description": "Military strongman who consolidated power following the 2019 coup. Central to Mauritania's geopolitical alignment, particularly on Western Sahara and bilateral relations with neighboring states. His security policies directly shape regional stability and Maghreb dynamics.",
    "affiliations": [
      "Government of Mauritania",
      "Military leadership"
    ],
    "countrySlug": "mauritania"
  },
  {
    "id": "mauritanian-military-establishment",
    "name": "Mauritanian Military Establishment (Armed Forces)",
    "type": "state",
    "role": "Primary state security force and political power broker",
    "riskContribution": "high",
    "description": "The military dominates Mauritanian politics and security apparatus following successive coups. Controls counterterrorism operations against jihadist groups in the north and maintains regional border security. Institutional power makes it a critical driver of state policy.",
    "affiliations": [
      "Government of Mauritania",
      "African Union"
    ],
    "countrySlug": "mauritania"
  },
  {
    "id": "al-qaida-islamic-maghreb-mauritania",
    "name": "Al-Qaeda in the Islamic Maghreb (AQIM)",
    "type": "non_state",
    "role": "Jihadist militant organization operating in the Sahel",
    "riskContribution": "high",
    "description": "Maintains active cells in Mauritania's northern regions, conducting sporadic attacks on security forces and civilian infrastructure. Exploits ungoverned spaces and tribal networks, creating persistent security threats and complicating state control of the Sahara.",
    "affiliations": [
      "Global jihadist movement"
    ],
    "countrySlug": "mauritania"
  },
  {
    "id": "brahim-ghali",
    "name": "Brahim Ghali",
    "type": "individual",
    "role": "Secretary-General of SADR (Sahrawi Arab Democratic Republic)",
    "riskContribution": "high",
    "description": "Leads the Polisario Front and the exiled SADR government, central to the decades-long Western Sahara independence dispute. His diplomatic and military decisions shape regional tensions and drive Algeria-Morocco conflict lines. Key figure in the unresolved decolonization question.",
    "affiliations": [
      "Polisario Front",
      "SADR",
      "African Union (recognition by 84+ states)"
    ],
    "countrySlug": "western-sahara"
  },
  {
    "id": "polisario-front-military",
    "name": "Polisario Front Armed Wings",
    "type": "non_state",
    "role": "Military and political liberation movement",
    "riskContribution": "high",
    "description": "The armed wing engages in sporadic armed conflict with Moroccan forces along disputed borders and maintains guerrilla operations in refugee camps. Serves as the primary military vehicle for Sahrawi independence claims and regional destabilization factor.",
    "affiliations": [
      "SADR",
      "Algeria (primary backer)",
      "African Union"
    ],
    "countrySlug": "western-sahara"
  },
  {
    "id": "sadr-administration",
    "name": "SADR (Sahrawi Arab Democratic Republic) Administration",
    "type": "state",
    "role": "Self-declared state authority in Western Sahara",
    "riskContribution": "medium",
    "description": "Operates government-in-exile from Algerian-controlled territories, recognized by African Union but not UN. Controls refugee camps and administers parallel institutions, perpetuating territorial dispute and regional fragmentation.",
    "affiliations": [
      "African Union",
      "Algeria",
      "Non-Aligned Movement"
    ],
    "countrySlug": "western-sahara"
  },
  {
    "id": "evariste-ndayishimiye",
    "name": "Évariste Ndayishimiye",
    "type": "individual",
    "role": "President of Burundi",
    "riskContribution": "high",
    "description": "Consolidated authoritarian control following disputed 2020 elections, continuing repression and political violence. His regime's human rights abuses, assassination allegations, and isolation from international community intensify internal fragmentation and regional mistrust.",
    "affiliations": [
      "CNDD-FDD (ruling party)",
      "Government of Burundi"
    ],
    "countrySlug": "burundi"
  },
  {
    "id": "burundi-security-forces",
    "name": "Burundian Security Forces (SNR/PNB)",
    "type": "state",
    "role": "State security apparatus and law enforcement",
    "riskContribution": "high",
    "description": "Extensively implicated in extrajudicial killings, torture, and arbitrary detention of political opponents. Functions as a key instrument of regime repression and ethnic targeting, undermining rule of law and sustaining cycles of communal violence.",
    "affiliations": [
      "Government of Burundi",
      "CNDD-FDD"
    ],
    "countrySlug": "burundi"
  },
  {
    "id": "burundi-opposition-movements",
    "name": "Burundian Opposition Coalition (CNARED/Diaspora Networks)",
    "type": "non_state",
    "role": "Fragmented opposition and civil resistance movements",
    "riskContribution": "medium",
    "description": "Scattered opposition and exile networks challenge regime authority through limited armed resistance and diplomatic isolation campaigns. Lacks cohesive structure but maintains capacity to generate political instability and regional refugee flows.",
    "affiliations": [
      "Democratic opposition",
      "International human rights organizations"
    ],
    "countrySlug": "burundi"
  }
]
